apiVersion: 1

datasources:
  - name: Influx
    type: influxdb
    access: proxy
    url: http://$INFLUX_HOST:$INFLUX_PORT
    isDefault: true
    database: $INFLUX_DB
    editable: true
    version: 1
